packages:
  - .

nodeLinker: hoisted
autoInstallPeers: false
minimumReleaseAgeExclude:
  - '@liustack/modlens@3.25.2 || 3.26.1'
  - '@liustack/modsearch@5.10.0 || 5.10.2'
  - dsh-builtin-browser@0.1.20
  - dshmarket@1.35.0 || 1.44.0 || 1.45.0
  - '@nanmicoder/dsh-agent-teams@0.1.16-rc.1'
  - dsh-quote-followup@0.2.5
  - dsh-context@0.46.0 || 0.49.1
  - '@linxin666/dsh-client-ui-community-plugins@0.3.20'
  - '@linxin666/dsh-client-ui-git-graph@0.3.20'
  - '@linxin666/dsh-client-ui-market@0.3.20'
  - '@linxin666/dsh-client-ui-model-capabilities@0.3.20'
  - '@linxin666/dsh-client-ui-plugin-manager@0.3.20'
  - '@linxin666/dsh-client-ui-preset-center@0.3.20'
  - '@linxin666/dsh-client-ui-skill-explorer@0.3.20'
  - '@linxin666/dsh-client-ui-skin-center@0.3.20'
  - '@linxin666/dsh-client-ui-task-board@0.3.20'
  - '@linxin666/dsh-client-ui-web-ui-settings@0.3.20'
  - '@linxin666/dsh-doctor@0.3.20'
  - '@linxin666/dsh-i18n@0.3.20'
  - '@linxin666/dsh-liangshen@0.3.20'
  - '@linxin666/dsh-pet@0.3.20'
  - '@linxin666/dsh-remote-web-ui@0.3.20'
  - '@linxin666/dsh-session-archive@0.3.20'
  - '@linxin666/dsh-ssh@0.3.20'
  - '@linxin666/dsh-tool-describe-image@0.3.20'
  - '@linxin666/dsh-usage@0.3.20'
  - '@linxin666/dsh-web-all@0.3.20'
  - dsh-better-sidebar@0.19.0-alpha.1 || 0.19.0
patchedDependencies:
  '@wxg-prc-cpg/browser-skill-dsh-plugin@0.2.1': patches/@wxg-prc-cpg__browser-skill-dsh-plugin@0.2.1.patch
allowBuilds:
  electron: true
  node-pty: true
  ssh2: true
  cloudflared: true
  cpu-features: true
