packages:
  - .

nodeLinker: hoisted
autoInstallPeers: false
minimumReleaseAgeExclude:
  - '@liustack/modlens@3.25.2 || 3.26.1'
  - '@liustack/modsearch@5.10.0 || 5.10.2'
  - dsh-builtin-browser@0.1.20
  - dshmarket@1.35.0 || 1.44.0 || 1.45.0
  - '@nanmicoder/dsh-agent-teams@0.1.16-rc.1'
  - dsh-quote-followup@0.2.5
  - dsh-context@0.46.0
allowBuilds:
  electron: true
  node-pty: true
  ssh2: true
  cloudflared: true
  cpu-features: true
